<div id='listar'>

	<div id='barra' class='quadro'>
		<div id='botoes'><!-- botões da lista -->
			<?php if (isset($this->listaBotoes)) : ?>
				<?php foreach($this->listaBotoes as $_botao => $_link) : ?>
					<input type='button' class='btForm' id='bt<?= ucfirst(strtolower($_botao)) ?>' onclick='javascript:document.location.href="<?= $_link ?>"' />
				<?php endforeach ?>
			<?php endif ?>
		</div>

		<div id='pesquisa'><!-- campos para pesquisa -->
			<?php if (isset($this->listaPesquisa)) : ?>
				<form>
				<?php foreach($this->listaPesquisa as $_campo => $_valor) : ?>
				<?php endforeach ?>
				</form>
			<?php endif ?>
		</div>

	</div>

	<div id='grade'>

		<div id='menu'><!-- subMenu -->
			<?php if (isset($this->subMenuModulos)) : ?>
			<ul>
				<?php foreach($this->subMenuModulos as $_titulo => $_link) : ?>
					<li><a href='<?= URL . $_link?>'<?= (strtolower($this->controllerName)==$_link) ? " class='cadastroAtivo'" : '' ?>><?=$_titulo?></a></li>
				<?php endforeach ?>
			</ul>
			<?php endif ?>
		</div>

		<div id='tabela'><!-- registros da página -->
			<table cellspacing='0px' cellpadding='0px'>

			<tr>
			<?php if (isset($this->listaCampos)) : ?>
			<?php foreach($this->listaCampos as $_campo) : ?>
				<th><a href=''><?= (isset($this->campos[$_campo]['label'])) ? $this->campos[$_campo]['label'] : $_campo ?></a></th>
			<?php endforeach ?>
				<th colspan='<?= count($this->listaFerramentas) ?>'></th>
			<?php endif ?>
			</tr>

			<?php if (isset($this->listaCampos)) : ?>
			<?php foreach($this->data as $_linha => $_arrCampos) : ?>
			<tr>
				<?php foreach($this->listaCampos as $_campo) : ?>
					<td<?php if(isset($this->campos[$_campo]['td'])) foreach($this->campos[$_campo]['td'] as $_tag => $_valor) echo " $_tag='$_valor'"; ?>>
						<?=$this->Mascara($_arrCampos[$_campo],(isset($this->campos[$_campo]['mascara'])) ? $this->campos[$_campo]['mascara'] : '' )?>
					</td>
				<?php endforeach ?>
				<?php foreach($this->listaFerramentas as $_campo => $_arrProp) : ?>
					<td align='center'>
						<a href='<?= $_arrProp['link'] ?>'><img src='<?= $_arrProp['img'] ?>' border='0'/></a>
					</td>
				<?php endforeach ?>
			</tr>
			<?php endforeach; ?>
			<?php endif ?>

			</table>
		</div>

	</div>

</div>
<?php if (!isset($this->listaCampos)) echo '<center>Os campos para lista não foram definidos !!!</center>' ?>
