<div id='info'>

<?php if (isset($this->usuario)) : ?>
	<h2>Informações do Usuário</h2>

	<dl>
	
	<?php foreach($this->usuario as $_campo => $_valor) : ?>
	
		<?php if (in_array($_campo,array('login','nome','email','ultimo_acesso','acessos'))) : ?>
	
			<dt><?=isset($this->campos[$_campo]['label'])? $this->campos[$_campo]['label'] : $_campo; ?></dt>
	
			<dd><?=$this->Mascara($_valor,(isset($this->campos[$_campo]['mascara'])) ? $this->campos[$_campo]['mascara'] : '' )?></dd>
	
		<?php endif; ?>
	
	<?php endforeach; ?>
	
	</dl>
<?php endif; ?>

<?php if (isset($this->perfis)) : ?>
	<h2>Perfis</h2>

	<dl>
		<?php foreach($this->perfis as $_campo => $_valor) : ?>
			<?php if (in_array($_campo,array('nome'))) : ?>
				<dt><?=$_campo?></dt><dd><?=$_valor?></dd>
			<?php endif; ?>
		<?php endforeach; ?>
	</dl>
<?php endif; ?>
</div>

<div id='fechar'><a href='listar'>Fechar</a></div>
