<?php
	// definindo a url
	define('URL', 'http://'.$_SERVER['SERVER_NAME'].$this->baseUrl().'/');

	$this->headMeta()->setHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headMeta()->appendName('keywords', 'zend, izend, php, framework');

	$this->headLink()->appendStylesheet(URL.'css/izend.css',array('media'=>'all'));
	if (file_exists('css/'.$this->controllerName.'.css')) $this->headLink()->appendStylesheet(URL.'css/'.$this->controllerName.'.css',array('media'=>'all'));
	if (file_exists('css/'.$this->actionName.'.css')) $this->headLink()->appendStylesheet(URL.'css/'.$this->actionName.'.css',array('media'=>'all'));
	
	$this->headScript()->appendFile(URL.'js/jquery-1.6.2.min.js');
	$this->headScript()->appendFile(URL.'js/izend.js');
	if (file_exists('js/'.$this->controllerName.'.js')) $this->headScript()->appendFile(URL.'js/'.$this->controllerName.'.js');
	if (file_exists('js/'.$this->actionName.'.js')) $this->headScript()->appendFile(URL.'js/'.$this->actionName.'.js');
	
	// opçõs do menu de módulos
	$opcModulos['Clientes'] = URL . 'clientes';
	$opcModulos['Sistema']	= URL . 'cidades';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle($this->titulo); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->headScript(); ?>


<script type="text/javascript">
$(document).ready (function()
{
	setTimeout(function(){ $("#msg").fadeOut(4000); },3000);
	<?php if (isset($this->on_read)) echo $this->on_read; ?>
});
</script>

<?php echo $this->headLink(); ?>

</head>

<body>
<div id="corpo">
	<div id="cabecalho">

		<div id='sigla'>
			<a href='<?=URL?>'><?=SISTEMA?></a><?php if (isset($this->posicao)) echo ' | '.$this->posicao; ?>
		</div>
		
		<div id='msg'>
			<?php if(isset($this->msg)) echo $this->msg; ?>
		</div>

		<div id="logos">
			<a href='http://www.zendbrasil.com.br/' target='_blanck'><img src='<?=URL?>img/zend_power.png'   border='none' alt='' /></a>
			<a href='http://www.jquery.com'  		target='_blanck'><img src='<?=URL?>img/jquery_power.png' border='none' alt='' /></a>
		</div>

		<div id='menu_modulos'>
		<?php if (isset($this->usuario['login'])) : ?>
			<ul>
				<?php foreach($opcModulos as $_titulo => $_link) : ?>
				<li><a href='<?=$_link ?>'><?= $_titulo ?></a> : </li>
				<?php endforeach; ?>
			</ul>
		<?php endif; ?>
		</div>

		<div id='menu_sistema'>
			<?php if (isset($this->menu_sistema)) : ?>
			<?php foreach($this->menu_sistema as $_campo => $_link) : ?>
			<li><a href='<?=URL.$_link?>'><?=$_campo?></a></li>
			<?php endforeach; ?>
			<?php endif; ?>
		</div>

		<div id='menu_usuario'>
			<?php if (isset($this->usuario['login'])) : ?>
			<a href='<?=URL?>usuarios/info'><?php echo $this->usuario['login']; ?></a> |
			<a href='<?=URL?>usuarios/sair'>sair</a>
			<?php else : ?>
			<a href='<?=URL?>usuarios/login'>login</a>
			<?php endif ?>
		</div>

	</div>

	<div id="conteudo">
		<?=$this->layout()->content?>

	</div>

</div>

</body>
</html>
